name: CI SDLC
on: [push]
jobs:
  phpstan-semgrep-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          ini-values: "memory_limit=-1"
          extensions: mbstring, intl
      - name: Download deps
        run: composer update --no-interaction --no-progress
      - name: Download PHPStan
        run: composer require --dev phpstan/phpstan #:1.5.x-dev
      - name: Download Larastan v1 # (Laravel Framework 6.20.44)
        run: composer require nunomaduro/larastan:^1.0 --dev
      - name: PHPStan version 
        run: vendor/bin/phpstan --version
      - name: Delete conflicting file
        run: rm -f database/migrations/2015_11_05_183749_image.php
      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze app config routes --no-progress --error-format=github -l 5
